CREATE DATABASE FATECSTORE;
USE FATECSTORE;

CREATE TABLE USUARIO (
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL 
);

CREATE TABLE PRODUTO (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  Marca VARCHAR(255) NOT NULL,
  Modelo VARCHAR(255) NOT NULL,
  Valor DECIMAL(10, 2) NOT NULL,
  Quantidade INT NOT NULL
);

CREATE TABLE VENDEDOR (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100),
    cpf VARCHAR(11),
    data_nascimento DATE,
    salario DECIMAL(10, 2),
    telefone VARCHAR(20),
    cargo VARCHAR(50),
    email VARCHAR(100),
    endereco VARCHAR(200)
);

CREATE TABLE CLIENTE (
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100),
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20),
    ENDERECO VARCHAR(200)
);

CREATE TABLE VENDA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CPF_CLIENTE VARCHAR(11),
    MARCA_PRODUTO VARCHAR(100),
    ID_VENDEDOR INT,
    MODELO_PRODUTO VARCHAR(100),
    QUANTIDADE INT,
    VALOR_PRODUTO DECIMAL(10, 2),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES vendedor(ID)
);

CREATE TABLE MARCA (
    id INT AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);